kconexo : k-conexo.o lib_kcon.o fila.o
	gcc -g -o kconexo k-conexo.o lib_kcon.o fila.o
k-conexo.o: k-conexo.c
	gcc -g -c -o k-conexo.o k-conexo.c
lib_kcon.o: lib_kcon.c
	gcc -g -c -o lib_kcon.o lib_kcon.c
fila.o: fila.c 
	gcc -g -c -o fila.o fila.c
